application: kberg-justchartit
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*\.(js|css))
  static_files: \1
  upload: .*\.(js|css)

- url: /save
  script: app.app
  login: required

- url: /foo
  script: app.app
  login: required

- url: /view
  script: app.app
  login: required

- url: /admin-list
  script: app.app
  login: required

- url: /_ah/login_required
  script: do_openid_login.app